version: 2
jobs:
  build:
    working_directory: ~/Deinok.Runtime.Serialization/
    docker:
      - image: microsoft/dotnet:1.1-sdk
    steps:

      - checkout

      - restore_cache:
          key: {{ .Branch }}

      - run: dotnet restore

      - save_cache:
          key: {{ .Branch }}
          paths:
            - /home/ubuntu/.nuget/

      - run: dotnet build

      - run: cd ./tests/Deinok.Runtime.Serialization.Tests/ && dotnet test
      - run: cd ./tests/Deinok.Runtime.Serialization.Base64.Tests/ && dotnet test
      - run: cd ./tests/Deinok.Runtime.Serialization.Bson.Tests/ && dotnet test
      - run: cd ./tests/Deinok.Runtime.Serialization.Json.Tests/ && dotnet test
