version: 2
jobs:
  build:
    working_directory: ~/Deinok.Runtime.Serialization/
    docker:
      - image: microsoft/dotnet:1.1-sdk
    steps:
      - checkout

      - restore_cache:
          key: Deinok.Runtime.Serialization

      # Compile
      - run: dotnet clean
      - run: dotnet restore
      - run: dotnet build
      
      - save_cache:
          key: Deinok.Runtime.Serialization
          paths:
            - ~/.nuget/

      # Test
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Tests/Deinok.Runtime.Serialization.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Base64.Tests/Deinok.Runtime.Serialization.Base64.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Bson.Tests/Deinok.Runtime.Serialization.Bson.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Json.Tests/Deinok.Runtime.Serialization.Json.Tests.csproj
      
      - deploy:
          name: MyGet
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apt install nuget
              nuget push ./src/Deinok.Runtime.Serialization/bin/Debug/Deinok.Runtime.Serialization.1.0.0.nupkg $MY_GET_API_KEY -Source https://www.myget.org/F/deinok/api/v2/package
            fi
