version: 2
jobs:
  build:
    working_directory: ~/Deinok.Runtime.Serialization/
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      MY_GET_SOURCE: https://www.myget.org/F/deinok-runtime-serialization/api/v3/index.json
    steps:
      - checkout
      
      # Test
      - restore_cache:
          key: NUGET
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Tests/Deinok.Runtime.Serialization.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Base64.Tests/Deinok.Runtime.Serialization.Base64.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Bson.Tests/Deinok.Runtime.Serialization.Bson.Tests.csproj
      - run: dotnet test ./tests/Deinok.Runtime.Serialization.Json.Tests/Deinok.Runtime.Serialization.Json.Tests.csproj
      - save_cache:
          key: NUGET
          paths:
            - ~/.nuget/
      
      # Artifacts
      - store_artifacts:
          path: ./src/Deinok.Runtime.Serialization/bin/Debug/Deinok.Runtime.Serialization.1.0.0.nupkg
          destination: Deinok.Runtime.Serialization.nupkg
      - store_artifacts:
          path: ./src/Deinok.Runtime.Serialization.Base64/bin/Debug/Deinok.Runtime.Serialization.Base64.1.0.0.nupkg
          destination: Deinok.Runtime.Serialization.Base64.nupkg
      - store_artifacts:
          path: ./src/Deinok.Runtime.Serialization.Bson/bin/Debug/Deinok.Runtime.Serialization.Bson.1.0.0.nupkg
          destination: Deinok.Runtime.Serialization.Bson.nupkg
      - store_artifacts:
          path: ./src/Deinok.Runtime.Serialization.Json/bin/Debug/Deinok.Runtime.Serialization.Json.1.0.0.nupkg
          destination: Deinok.Runtime.Serialization.Json.nupkg
          
      - deploy:
          name: MyGet
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet nuget push ./src/Deinok.Runtime.Serialization/bin/Debug/Deinok.Runtime.Serialization.1.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
              dotnet nuget push ./src/Deinok.Runtime.Serialization.Base64/bin/Debug/Deinok.Runtime.Serialization.Base64.1.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
              dotnet nuget push ./src/Deinok.Runtime.Serialization.Bson/bin/Debug/Deinok.Runtime.Serialization.Bson.1.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
              dotnet nuget push ./src/Deinok.Runtime.Serialization.Json/bin/Debug/Deinok.Runtime.Serialization.Json.1.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
            fi
